apiVersion: apps/v1
kind: Deployment
metadata:
  name: "frontend-deployment"
  namespace: "2048-game"
spec:
  selector:
    matchLabels:
      app: "frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
      - name: "frontend"
        image: public.ecr.aws/nginx/nginx:1.23
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
